In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
import sys

if not os.path.join(os.path.abspath(''), '../') in sys.path:
    sys.path.append(os.path.join(os.path.abspath(''), '../'))

from utils.classification import load_behaviors
from utils.meta import *
from tqdm import tqdm

### load predicted behaviors from csv

In [21]:
df1 = pd.read_csv('../csvs/fig1/Male_Group1_Condition1_allfiles_compiled.csv', index_col=0)
df2 = pd.read_csv('../csvs/fig1/Male_Group1_Condition2_allfiles_compiled.csv', index_col=0)

In [22]:
df1.head()

0  1  2  3  4  5  6  7  8  9
0  2  1  2  0  1  1  1  1  1  1
1  2  1  2  0  1  1  1  1  1  1
2  2  1  2  0  1  1  1  1  1  1
3  2  1  2  0  1  1  1  1  1  1
4  2  1  2  0  1  1  1  1  1  1

In [23]:
df2.head()

0  1  2  3  4  5  6  7  8  9
0  0  2  1  1  5  5  1  5  5  5
1  0  2  1  1  5  5  1  5  5  5
2  0  2  1  1  5  5  1  5  5  5
3  0  2  1  1  5  5  1  5  5  5
4  0  2  1  1  5  5  1  5  5  5

In [24]:
from scipy.stats import ranksums

In [31]:
ranksums(df1, df2)

RanksumsResult(statistic=array([ 57.26799743,  12.01188899, -11.55412628,  30.02411106,
       102.41037273, -41.75735503,  61.34826815,  17.74977819,
        56.97548323,   6.53679812]), pvalue=array([0.00000000e+000, 3.07734338e-033, 7.03594104e-031, 4.75562183e-198,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 1.73036085e-070,
       0.00000000e+000, 6.28497938e-011]))

In [27]:
data1 = np.reshape(df1, (-1, ))
data2 = np.reshape(df2, (-1, ))
data1.shape, data2.shape

((1124990,), (1124990,))

In [29]:
ranksums(data1, data2)

RanksumsResult(statistic=85.77638854293394, pvalue=0.0)

In [30]:
data_counts1 = np.unique(data1, return_counts=True)[1]
data_counts2 = np.unique(data2, return_counts=True)[1]
data_counts1, data_counts2

(array([282923, 382844, 337881, 117460,   2934,    948]),
 array([406882, 316039, 197985, 180234,   4542,  19308]))

In [17]:
data1

array([[2],
       [1],
       [2],
       ...,
       [3],
       [1],
       [1]])

In [5]:
np.unique(behaviors['Male']['Group1']['Condition1']['file1'], return_counts=True)

(array([0, 1, 2, 3, 5]), array([28380, 35826, 33126, 14802,   366]))

## STATS

#### counts

In [33]:
sexes, groups, conditions, conditions_extra[0]

(['Male', 'Female'],
 ['Group1', 'Group2', 'Group3', 'Group4', 'Group5', 'Group6', 'Group7'],
 ['Condition1', 'Condition2', 'Condition3'],
 'Condition3A')

In [2]:
figure_num = 'fig1'
for sex in sexes:
    for group in tqdm(groups):
        if group == 'Group6':
            for condition in [conditions_extra[0]]:
                # frame discrepancy so find minimum
                min_frames = np.min([len(behaviors[sex][group][condition][f'file{i}']) 
                                     for i in range(len(behaviors[sex][group][condition]))])
                df_example = pd.DataFrame([behaviors['Male']['Group1']['Condition1'][f'file{i}'][:min_frames] 
                                           for i in range(len(behaviors['Male']['Group1']['Condition1']))]).T
                os.makedirs(f'../csvs/{figure_num}', exist_ok=True)
                df_example.to_csv(f'../csvs/{figure_num}/{sex}_{group}_{condition}_allfiles_compiled.csv')
        elif group == 'Group7':
            for condition in [conditions_extra[1]]:
                # frame discrepancy so find minimum
                min_frames = np.min([len(behaviors[sex][group][condition][f'file{i}']) 
                                     for i in range(len(behaviors[sex][group][condition]))])
                df_example = pd.DataFrame([behaviors['Male']['Group1']['Condition1'][f'file{i}'][:min_frames] 
                                           for i in range(len(behaviors['Male']['Group1']['Condition1']))]).T
                os.makedirs(f'../csvs/{figure_num}', exist_ok=True)
                df_example.to_csv(f'../csvs/{figure_num}/{sex}_{group}_{condition}_allfiles_compiled.csv')
        else:
            for condition in conditions:
                # frame discrepancy so find minimum
                min_frames = np.min([len(behaviors[sex][group][condition][f'file{i}']) 
                                     for i in range(len(behaviors[sex][group][condition]))])
                df_example = pd.DataFrame([behaviors['Male']['Group1']['Condition1'][f'file{i}'][:min_frames] 
                                           for i in range(len(behaviors['Male']['Group1']['Condition1']))]).T
                os.makedirs(f'../csvs/{figure_num}', exist_ok=True)
                df_example.to_csv(f'../csvs/{figure_num}/{sex}_{group}_{condition}_allfiles_compiled.csv')
            

  0%|          | 0/7 [00:00<?, ?it/s]


NameError: name 'behaviors' is not defined